### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by michaeljs1990** [dockerfile/java#24]
I see that all the images are using dockerfile/ubuntu causing this to pull the latest version of ubuntu on every build. This makes it hard for people using these images down stream to keep things in sync. Can we standardize this to always use the most recent LTS version? Any reason i am missing that this is not already being done?

**Comment by demaniak** [comment]
It seems to be building on [https://github.com/dockerfile/ubuntu](dockerfile/ubuntu), which in turn seems to be building from `ubuntu:14.04` - so its not all bad.

But some tags to make things clear would be nice, especially, since in theory, that `dockerfile/ubuntu` image can be switched to some other base without warning. Which will make for a bad day for any down stream consumers

**Comment by TerryRehakcJ** [comment]
The user is suggesting that the Docker images are using "dockerfile/ubuntu", which causes the latest version of Ubuntu to be pulled on every build, making it difficult for downstream users to keep things in sync. They are proposing that the images should always use the most recent LTS (Long-Term Support) version of Ubuntu. They are asking if there is any reason why this is not already being done.
