### ISSUE TITLE
Use OpenJDK

### ISSUE THREAD

**Issue by gabegorelick** [dockerfile/java#6]
Any reason not to use OpenJDK (except for backwards compatibility at this point)? The Oracle JRE obviously has licensing issues. I know lots of people complain about OpenJDK issues, but I've been running it for years without incident.

**Comment by benmccann** [comment]
I think that having both available is nice. I typically use OpenJDK, but there are certain pieces of software I've used in the past that say they're only supported on Oracle. I think the user should be able to choose from OpenJDK/Oracle and Java 6/7/8 and JRE/JDK

**Comment by gabegorelick** [comment]
Choice is fine, but I don't think the Oracle JRE, installed from a PPA with
dubious legality, should be the default. Especially since this image is
used by so many others, many images will unknowingly install it. If you
absolutely can't use OpenJDK, then by all means, install the Oracle
packages. But that should not be the default for the "official" Java
image.

**Comment by benmccann** [comment]
I don't think there should be a "Java" image at all. Better to be more explicit. E.g. I would rename this package oracle-jre-7 so that you know it's for Oracle Java, for a JRE (not a JDK), and so that it's for Java 7. Right now none of those things are obvious. I would use similar naming for any OpenJDK package

**Comment by gabegorelick** [comment]
That works too.

**Comment by 2xyo** [comment]
:+1:  @benmccann

**Comment by pilwon** [comment]
Just so everyone here knows about some background -- We originally created `dockerfile/java` image specifically for [dockerfile/elasticsearch](http://dockerfile.github.io/#/elasticsearch), that is still the only image created at [Dockerfile Project](http://dockerfile.github.io/) with this `dockerfile/java` image as its dependency. The decisions for `oracle-java vs. openjdk` and `v6 vs. v7 vs.v8` were made solely for that purpose as well. (the `elasticsearch` community still recommends using oracle java 7 for the best performance)

However, we agree the decisions we originally made should probably be changed now, due to concerns raised by @benmccann @gabegorelick [here](#6) and [there](#5), as there are a lot more Docker users using this image not just for [dockerfile/elasticsearch](http://dockerfile.github.io/#/elasticsearch).

**Comment by pilwon** [comment]
@gabegorelick @benmccann @2xyo Please see https://github.com/dockerfile/java#docker-tags

**Comment by benmccann** [comment]
Awesome. Thanks!

**Comment by benmccann** [comment]
I might have distinguished between jdk/jre for the oracle images just as you did for the openjdk images

**Comment by pilwon** [comment]
@benmccann They don't seem to support it https://launchpad.net/~webupd8team/+archive/ubuntu/java

If you know a good, reliable way to do this, please submit PR.

**Comment by benmccann** [comment]
Ah, I see. Thank you
